### ISSUE TITLE
The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by capsloq** [MaksZhukov/strapi-plugin-generate-data#30]
Hello,

on a fresh install of Strapi 4.5.1 (javascript no typescript) i am getting this error when enabling the pulgin:

```PS F:\Projekte\maklersuite-backend> yarn develop
yarn run v1.22.17
$ strapi develop
[2022-11-19 14:56:35.539] debug: ⛔️ Server wasn't able to start properly.
[2022-11-19 14:56:35.542] error: The "path" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:393:5)
    at validateString (node:internal/validators:163:11)
    at join (node:path:429:7)
    at Object.loadPlugins (F:\Projekte\maklersuite-backend\node_modules\@strapi\strapi\lib\core\loaders\plugins\index.js:88:34)
    at async Strapi.loadPlugins (F:\Projekte\maklersuite-backend\node_modules\@strapi\strapi\lib\Strapi.js:333:5)
    at async Promise.all (index 2)
    at async Strapi.register (F:\Projekte\maklersuite-backend\node_modules\@strapi\strapi\lib\Strapi.js:369:5)
    at async Strapi.load (F:\Projekte\maklersuite-backend\node_modules\@strapi\strapi\lib\Strapi.js:474:5)
    at async Strapi.start (F:\Projekte\maklersuite-backend\node_modules\@strapi\strapi\lib\Strapi.js:212:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this `command.
```

config/plugins.js
```
module.exports = ({ env }) => ({
    "generate-data": {
        enabled: true,
    },
});
```

**Comment by MaksZhukov** [comment]
@capsloq Hey! Whick version of nodejs do you use?

**Comment by capsloq** [comment]
@MaksZhukov node 18

**Comment by MaksZhukov** [comment]
@capsloq Could you check with the latest version?
