### ISSUE TITLE
Generate Images + Video and get error cause the crash app.

### ISSUE THREAD

**Issue by chungnq253** [MaksZhukov/strapi-plugin-generate-data#40]
**Request info:**

`curl 'http://localhost:1337/generate-data/upload' \
  -H 'Accept: application/json' \
  -H 'Accept-Language: en-US,en;q=0.9,vi-VN;q=0.8,vi;q=0.7,fr-FR;q=0.6,fr;q=0.5' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk0NDAwODU0LCJleHAiOjE2OTUwMDU2NTR9.vM64f10tks_-qVf335_WMlrsHNYaBXbnoeBSIb_BKw8' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: 5d89dac18813e15aa2f75788275e3588=ithprgaddacmchk3u1bo0mbqds; collapsedNodes=' \
  -H 'Origin: http://localhost:1337' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '{"fileUpload":[["https://loremflickr.com/640/480/people?lock=57698","https://loremflickr.com/640/480/cats?lock=97017"],["/generate-data/videos/7.mp4","/generate-data/videos/3.mp4","/generate-data/videos/3.mp4"],["/generate-data/videos/6.mp4"],["/generate-data/videos/7.mp4","/generate-data/videos/10.mp4"],["/generate-data/videos/4.mp4"],["https://loremflickr.com/640/480/food?lock=28923","https://loremflickr.com/640/480/food?lock=10975"],["https://loremflickr.com/640/480/cats?lock=91417","https://loremflickr.com/640/480/animals?lock=21913"],["/generate-data/videos/5.mp4"],["/generate-data/audios/2.wav","/generate-data/audios/4.wav","/generate-data/audios/1.wav"],["/generate-data/videos/1.mp4","/generate-data/videos/3.mp4","/generate-data/videos/4.mp4"]]}' \
  --compressed`
  

**Command output:**

`[2023-09-11 02:55:48.730] http: GET /content-manager/collection-types/api::article.article?fields[0]=id&page=1 (169 ms) 200
[2023-09-11 02:55:48.772] http: GET /content-manager/collection-types/api::assistance-type.assistance-type?fields[0]=id&page=1 (207 ms) 200
[2023-09-11 02:55:48.786] http: GET /content-manager/collection-types/api::category.category?fields[0]=id&page=1 (209 ms) 200
[2023-09-11 02:55:48.813] http: GET /content-manager/collection-types/api::state.state?fields[0]=id&page=1 (231 ms) 200
[2023-09-11 02:55:48.855] http: GET /content-manager/collection-types/plugin::users-permissions.user?fields[0]=id&page=1 (275 ms) 200
[2023-09-11 02:55:49.047] http: GET /content-manager/collection-types/api::submission.submission?fields[0]=id&page=1 (474 ms) 200
[2023-09-11 02:55:49.150] http: GET /content-manager/collection-types/api::submission.submission?fields[0]=id&page=1 (101 ms) 200
[2023-09-11 02:55:49.291] http: GET /content-manager/collection-types/api::submission.submission?fields[0]=id&page=1 (137 ms) 200
[2023-09-11 02:55:49.407] http: GET /content-manager/collection-types/api::submission.submission?fields[0]=id&page=1 (111 ms) 200
[2023-09-11 02:55:49.505] http: GET /generate-data/videos/3.mp4 (7 ms) 200
[2023-09-11 02:55:49.514] http: GET /generate-data/videos/7.mp4 (8 ms) 200
[2023-09-11 02:55:49.520] http: GET /generate-data/videos/6.mp4 (5 ms) 200
[2023-09-11 02:55:49.521] http: GET /generate-data/videos/10.mp4 (25 ms) 404
[2023-09-11 02:55:49.525] http: GET /generate-data/videos/3.mp4 (2 ms) 200
[2023-09-11 02:55:49.562] http: GET /generate-data/videos/7.mp4 (36 ms) 200
[2023-09-11 02:55:49.591] http: GET /generate-data/videos/4.mp4 (22 ms) 200
[2023-09-11 02:55:49.685] http: GET /generate-data/videos/5.mp4 (32 ms) 200
[2023-09-11 02:55:49.811] http: GET /generate-data/audios/2.wav (121 ms) 200
[2023-09-11 02:55:49.858] http: GET /generate-data/audios/4.wav (45 ms) 200
[2023-09-11 02:55:49.892] http: GET /generate-data/audios/1.wav (23 ms) 200
[2023-09-11 02:55:49.898] http: GET /generate-data/videos/3.mp4 (5 ms) 200
[2023-09-11 02:55:49.915] http: GET /generate-data/videos/1.mp4 (15 ms) 200
[2023-09-11 02:55:49.925] http: GET /generate-data/videos/4.mp4 (7 ms) 200
[AxiosError: Request failed with status code 404] {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function] },
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.27.2'
    },
    responseType: 'stream',
    httpsAgent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 0,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    method: 'get',
    url: '/generate-data/videos/5.mp4',
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(async_id_symbol)]: 289684,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: true,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _header: 'GET /generate-data/videos/5.mp4 HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: axios/0.27.2\r\n' +
      'Host: [::1]\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 14,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/generate-data/videos/5.mp4',
    _ended: false,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'http://[::1]/generate-data/videos/5.mp4',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 10,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: '::1',
    protocol: 'http:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'http://[::1]/generate-data/videos/5.mp4',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 404,
    statusText: 'Not Found',
    headers: {
      date: 'Mon, 11 Sep 2023 02:56:08 GMT',
      server: 'Apache',
      'content-length': '196',
      connection: 'close',
      'content-type': 'text/html; charset=iso-8859-1'
    },
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object],
      responseType: 'stream',
      httpsAgent: [Agent],
      method: 'get',
      url: '/generate-data/videos/5.mp4',
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /generate-data/videos/5.mp4 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.27.2\r\n' +
        'Host: [::1]\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/generate-data/videos/5.mp4',
      _ended: false,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '::1',
      protocol: 'http:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    data: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [ClientRequest],
      responseUrl: 'http://[::1]/generate-data/videos/5.mp4',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 10,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    }
  }
}
[2023-09-11 02:56:08.679] http: POST /generate-data/upload (64 ms) 200
[2023-09-11 02:56:08.689] http: POST /generate-data/create/api::submission.submission (5 ms) 200
/Users/chungnq253/Projects/xpon/att/att-cms/node_modules/@strapi/utils/dist/validators.js:86
    throw new errors_1.YupValidationError(error, errorMessage);
          ^

YupValidationError: select count("t0"."id") as "count" from "public"."files" as "t0" where ("t0"."id" in ($1)) limit $2 - invalid input syntax for type integer: "/generate-data/videos/6.mp4"
    at handleYupError (/Users/chungnq253/Projects/xpon/att/att-cms/node_modules/@strapi/utils/dist/validators.js:86:11)
    at /Users/chungnq253/Projects/xpon/att/att-cms/node_modules/@strapi/utils/dist/validators.js:98:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.create (/Users/chungnq253/Projects/xpon/att/att-cms/node_modules/@strapi/strapi/lib/services/entity-service/index.js:156:23)
    at async Object.<anonymous> (/Users/chungnq253/Projects/xpon/att/att-cms/node_modules/@strapi/strapi/lib/services/entity-service/index.js:415:20)
    at async Object.create (/Users/chungnq253/Projects/xpon/att/att-cms/node_modules/@strapi/plugin-i18n/server/services/entity-service-decorator.js:130:19) {
  details: {
    errors: [
      {
        path: [],
        message: 'select count("t0"."id") as "count" from "public"."files" as "t0" where ("t0"."id" in ($1)) limit $2 - invalid input syntax for type integer: "/generate-data/videos/6.mp4"',
        name: 'ValidationError'
      }
    ]
  }
}

Node.js v18.16.1
✨  Done in 229.40s.`

<img width="1550" alt="image" src="https://github.com/MaksZhukov/strapi-plugin-generate-data/assets/44595953/f4193ee1-8c08-40e5-af7c-92213b0743b8">

**Comment by MaksZhukov** [comment]
@chungnq253 Hey! Could you check the latest version?

**Comment by chungnq253** [comment]
I have a new error when updating the latest version @MaksZhukov !!

My screen Capture: https://jam.dev/c/2bcea29e-efa6-411b-b3fd-6b02db288107

**Package.json dependencies:**
`  "dependencies": {
    "@strapi/plugin-graphql": "4.13.6",
    "@strapi/plugin-i18n": "4.13.6",
    "@strapi/plugin-seo": "^1.9.5",
    "@strapi/plugin-users-permissions": "4.13.6",
    "@strapi/provider-email-sendgrid": "4.13.7",
    "@strapi/provider-upload-cloudinary": "4.13.6",
    "@strapi/provider-upload-local": "4.13.6",
    "@strapi/strapi": "4.13.6",
    "add": "^2.0.6",
    "better-sqlite3": "8.0.1",
    "form-data": "^4.0.0",
    "graphql-tag": "^2.12.6",
    "iso-3166-1": "^2.1.1",
    "lodash": "^4.17.21",
    "ms": "^2.1.3",
    "node-fetch": "2.6.12",
    "npm-run-all": "^4.1.5",
    "patch-package": "^7.0.2",
    "pg": "^8.11.1",
    "rimraf": "^5.0.1",
    "strapi-blurhash": "^1.1.1",
    "strapi-plugin-config-sync": "^1.1.2",
    "strapi-plugin-generate-data": "^1.0.29",
    "strapi-plugin-import-export-entries": "^1.21.1",
    "strapi-plugin-init-admin-user": "^0.2.1",
    "strapi-plugin-navigation": "^2.2.11",
    "supertest-graphql": "^1.1.4"
  },`

**Terminal error output:** 
`yarn run v1.22.19
$ strapi develop
Starting the compilation for TypeScript files in /Users/chungnq253/Projects/xpon/att/att-cms
[2023-10-18 16:40:58.798] warn: Users-permissions registration has defaulted to accepting the following additional user fields during registration: submissions,profile,source

 Project information

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Wed Oct 18 2023 16:40:59 GMT+0000 (Coordinated … │
│ Launched in        │ 2584 ms                                          │
│ Environment        │ development                                      │
│ Process PID        │ 85276                                            │
│ Version            │ 4.13.6 (node v18.16.1)                           │
│ Edition            │ Community                                        │
│ Database           │ postgres                                         │
└────────────────────┴──────────────────────────────────────────────────┘

 Actions available

Welcome back!
To manage your project 🚀, go to the administration panel at:
http://localhost:1337/admin

To access the server ⚡️, go to:
http://localhost:1337

[2023-10-18 16:41:01.277] http: GET /admin/plugins/generate-data?typeUID=api%3A%3Aassistance-type.assistance-type (20 ms) 200
[2023-10-18 16:41:01.519] http: GET /admin/project-type (14 ms) 200
[2023-10-18 16:41:01.838] http: POST /admin/renew-token (22 ms) 200
[2023-10-18 16:41:01.857] http: GET /admin/init (16 ms) 200
[2023-10-18 16:41:01.933] http: GET /admin/telemetry-properties (70 ms) 200
[2023-10-18 16:41:01.991] http: GET /admin/information (39 ms) 200
[2023-10-18 16:41:02.050] http: GET /admin/users/me (95 ms) 200
[2023-10-18 16:41:02.092] http: GET /admin/users/me/permissions (139 ms) 200
[2023-10-18 16:41:02.134] http: GET /i18n/locales (33 ms) 200
[2023-10-18 16:41:02.467] http: GET /content-type-builder/content-types (82 ms) 200
[2023-10-18 16:41:02.768] http: GET /content-manager/collection-types/api::submission.submission?pageSize=1 (283 ms) 200
[2023-10-18 16:41:49.232] http: GET /generate-data/audios/5.wav (8 ms) 200
[2023-10-18 16:41:49.262] http: GET /generate-data/videos/10.mp4 (26 ms) 200
[2023-10-18 16:41:49.271] http: GET /generate-data/videos/5.mp4 (3 ms) 200
[2023-10-18 16:41:49.275] http: GET /generate-data/audios/1.wav (1 ms) 200
[2023-10-18 16:41:49.280] http: GET /generate-data/audios/1.wav (1 ms) 200
[2023-10-18 16:41:49.295] http: GET /generate-data/videos/3.mp4 (7 ms) 200
[2023-10-18 16:41:49.302] http: GET /generate-data/videos/4.mp4 (6 ms) 200
[2023-10-18 16:41:49.323] http: GET /generate-data/videos/4.mp4 (2 ms) 200
[2023-10-18 16:41:49.336] http: GET /generate-data/audios/1.wav (8 ms) 200
[2023-10-18 16:41:49.342] http: GET /generate-data/videos/2.mp4 (5 ms) 200
[2023-10-18 16:42:01.587] error: ctx.InternalServerError is not a constructor
TypeError: ctx.InternalServerError is not a constructor
    at Object.<anonymous> (/Users/chungnq253/Projects/xpon/att/att-cms/node_modules/strapi-plugin-generate-data/server/controllers/my-controller.js:102:51)
    at step (/Users/chungnq253/Projects/xpon/att/att-cms/node_modules/strapi-plugin-generate-data/server/controllers/my-controller.js:33:23)
    at Object.throw (/Users/chungnq253/Projects/xpon/att/att-cms/node_modules/strapi-plugin-generate-data/server/controllers/my-controller.js:14:53)
    at rejected (/Users/chungnq253/Projects/xpon/att/att-cms/node_modules/strapi-plugin-generate-data/server/controllers/my-controller.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-10-18 16:42:01.597] http: POST /generate-data/create/api::assistance-type.assistance-type (5 ms) 200
/Users/chungnq253/Projects/xpon/att/att-cms/node_modules/@strapi/utils/dist/validators.js:86
    throw new errors_1.YupValidationError(error, errorMessage);
          ^

YupValidationError: select count("t0"."id") as "count" from "public"."files" as "t0" where ("t0"."id" in ($1, $2, $3, $4)) limit $5 - invalid input syntax for type integer: "https://loremflickr.com/640/480/nature?lock=7230959313223680"
    at handleYupError (/Users/chungnq253/Projects/xpon/att/att-cms/node_modules/@strapi/utils/dist/validators.js:86:11)
    at /Users/chungnq253/Projects/xpon/att/att-cms/node_modules/@strapi/utils/dist/validators.js:98:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.create (/Users/chungnq253/Projects/xpon/att/att-cms/node_modules/@strapi/strapi/lib/services/entity-service/index.js:156:23)
    at async Object.<anonymous> (/Users/chungnq253/Projects/xpon/att/att-cms/node_modules/@strapi/strapi/lib/services/entity-service/index.js:416:20)
    at async Object.create (/Users/chungnq253/Projects/xpon/att/att-cms/node_modules/@strapi/plugin-i18n/server/services/entity-service-decorator.js:130:19) {
  details: {
    errors: [
      {
        path: [],
        message: 'select count("t0"."id") as "count" from "public"."files" as "t0" where ("t0"."id" in ($1, $2, $3, $4)) limit $5 - invalid input syntax for type integer: "https://loremflickr.com/640/480/nature?lock=7230959313223680"',
        name: 'ValidationError'
      }
    ]
  }
}

Node.js v18.16.1
✨  Done in 69.21s.`

**Comment by chungnq253** [comment]
Nicely done with http://127.0.0.1:1337/ @MaksZhukov 🚀 🚀 🚀
